import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'

import { getSession } from 'next-auth/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home

// This page will be user home page, not signed in will be able to view profiles and repos but not the home page
// As it contains private repos of the person

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/home',
        permanent: false,
      },
    }
  }

  return {
    props: { session },
  }
}
